version = 0.1

[default.deploy.parameters]
stack_name = "coincompanion"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "coincompanion"
profile = "personal"
image_repositories = []
disable_rollback = false
parameter_overrides = [
"EmailSender=example@example.com",
"CoinCompanionPriceHistoryUrl=https://apiexample.com/prod/internal/price/history"
]

