name: SAM Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      # Step 3: Install SAM CLI
      - name: Install SAM CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install aws-sam-cli

      # Step 4: Deploy using SAM CLI with parameters passed manually
      - name: Deploy SAM Application
        run: |
          sam deploy --no-confirm-changeset \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
            "EmailSender=${{ secrets.EMAIL_SENDER }}" \
            "CoinCompanionPriceHistoryUrl=${{ secrets.COINCOMPANION_PRICE_HISTORY_URL }}" \
            --stack-name coincompanion \
            --region ap-southeast-2 \
            --s3-prefix coincompanion \
            --disable-rollback \
            --resolve-s3 \
            --profile personal
